POST http://localhost:5500/api/send-otp-email HTTP/1.1
Content-Type: application/json

{
    "email": "vodojok274@konican.com"
}

###
POST http://localhost:5500/api/verify-otp-email HTTP/1.1
Content-Type: application/json

{
    "email": "vodojok274@konican.com",
    "otp": 5671,
    "hash": "a4731a3a17fcf6914fe3ac811f33a518030aca146587124c4e55e6ca6a824cb3.1705810404382"
}

